# Generated by Django 4.0.2 on 2022-03-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
