# Generated by Django 4.0.2 on 2022-03-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0003_remove_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
