# Generated by Django 4.0.2 on 2022-03-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0008_alter_film_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.CharField(default=2021, max_length=100),
            preserve_default=False,
        ),
    ]
