# Generated by Django 4.0.2 on 2022-03-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0009_film_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.TextField(),
        ),
    ]
