# Generated by Django 4.0.2 on 2022-03-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0010_alter_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.JSONField(),
        ),
    ]
